POST http://localhost:3000/registro
Content-Type: application/json 

{
  "nombre": "Maria",
  "mensaje": "Hola comunidad"
}

### ejemplo incidencias
POST http://localhost:3000/incidencia 
Content-Type: application/json 

{
  "tipo": "Iluminación pública",
  "descripcion": "La comunidad reporta que una lámpara del parque no funciona desde hace varios días."
}